[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "homesense-adb-cli"
version = "0.1.0"
description = "HomeSense ADB CLI source project"
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
adb-cli = "main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["adb_cli*"]
